env:
  global:
    - PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}

matrix:
  include:
    - language: python
      python: "3.6"

      name: "Python Test"

      script:
        - noobaa-core/src/test/python_test/python_test.py

