env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config
    - LOCAL_IP=$(ifconfig | grep inet | head -1 | awk '{print $2}' | cut -d':' -f2)

    - IMAGE_TAG="noobaa-${TRAVIS_COMMIT}"
    - TESTER_TAG="noobaa-tester-${TRAVIS_COMMIT}"

matrix:
  include:
    - language: python
      python: "3.6"

      name: "Python Test"

      install:
          - pip install gitpython
          -  pip install os_sys
          - pip install .

      script:
        - noobaa-core/src/test/python_test/python_test.py

